spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/ycf?useUnicode=true&characterEncoding=utf8
     username: root
     password: admin
     driver-class-name: com.mysql.jdbc.Driver

elasticSearch:
  #host: 192.168.3.93     #公司测试服务器的ES地址
  host: 192.168.10.126   #本地虚拟机上的ES地址
  port: 9200
  client:
    connectNum: 10
    connectPerRoute: 50

server:
  port: 8888